name: s3plugin build
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'maven'

    - name: Cache Maven local repo
      uses: actions/cache@v3
      with:
        path: |
          ~/.m2/repository
          ${{ github.workspace }}/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Build with Maven
      run: mvn -B install

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: hpi-artifact
        path: target/s3trigger.hpi


    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v1.0.1
        name: Release v1.0.1
        body: |-
          Release notes here
          - Feature 1
          - Bug fix 2
        draft: false
        prerelease: false
        files: |
          target/s3trigger.hpi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
