name: Maven Build
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '21' # or your preferred version
        distribution: 'temurin'
        cache: 'maven' # Automatic Maven dependency caching

    - name: Build with Maven
      run: mvn -B install

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: plugin-artifact
        path: target/s3trigger.hpi
        retention-days: 180
