name: s3plugin build
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'maven'

    - name: Cache Maven local repo
      uses: actions/cache@v3
      with:
        path: |
          ~/.m2/repository
          ${{ github.workspace }}/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Build with Maven
      run: mvn -B install

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: hpi-artifact
        path: target/s3trigger.hpi
